apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-api-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: short-api
          image: antonlarichev/short-api:v1.0
          # imagePullPolicy: Always   # will always pull the new image, better use tag, not latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: DATABASE_URL
              valueFrom: 
                secretKeyRef:
                  name: short-api-secret
                  key: DATABASE_URL      
  