apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: short-api
          image: antonlarichev/short-api:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: short-api-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: test
              mountPath: /etc/test
              readOnly: true
          # livenessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - --fail
          #       - http://localhost:3000/api
          #   initialDelaySeconds: 100
          #   periodSeconds: 5
          #   failureThreshold: 1
          # startupProbe:
          #   exec:
          #     command:
          #       - curl
          #       - --fail
          #       - http://localhost:3000/api
          #   periodSeconds: 10
          #   failureThreshold: 5
          # readinessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - --fail
          #       - http://localhost:3000/api
          #   periodSeconds: 10 
          #   initialDelaySeconds: 10
      volumes:
      - name: test
        configMap:
          name: demo-config
        